name: Build, Test & Publish Docker Image

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  IMAGE_NAME: atuljkamble/docker-basic-website

jobs:
  test-image:
    name: Build & Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (local) for tests
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true           # load into local Docker engine for run/curl
          tags: ${{ env.IMAGE_NAME }}:test

      - name: Run container
        run: |
          docker run -d --rm -p 8080:80 --name webtest $IMAGE_NAME:test
          # give nginx a moment
          for i in {1..20}; do
            if curl -fsS http://localhost:8080/ >/dev/null; then
              echo "App is responding ✅"
              exit 0
            fi
            echo "Waiting for app... ($i)"
            sleep 1
          done
          echo "App did not become healthy in time"; docker logs webtest || true
          exit 1

      - name: Stop container
        if: always()
        run: docker ps -a && docker stop webtest || true

  build-and-push:
    name: Buildx & Push to Docker Hub
    runs-on: ubuntu-latest
    needs: test-image
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=sha,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
